"""Update HOSTS.txt, regenerate blocklist.json, write review queue."""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

import config


def _parse_line(line: str) -> str | None:
    """Extract a normalized domain from a single hosts-format or plain line.

    Accepts both '0.0.0.0 domain' and bare 'domain' formats.
    Returns None for comments, blanks, and unparseable lines.
    """
    line = line.strip()
    if not line or line.startswith('#'):
        return None
    # Lazy import to avoid circular dependency at module load
    from ingest import normalize_domain
    if line.startswith('0.0.0.0') or line.startswith('127.0.0.1'):
        parts = line.split()
        if len(parts) >= 2:
            return normalize_domain(parts[1])
        return None
    # Bare domain
    return normalize_domain(line)


def load_existing_hosts_set() -> set[str]:
    """Load existing domains from HOSTS.txt (accepts both formats)."""
    path = Path(config.HOSTS_FILE)
    if not path.exists():
        return set()
    domains: set[str] = set()
    for line in path.read_text(encoding='utf-8', errors='ignore').splitlines():
        d = _parse_line(line)
        if d:
            domains.add(d)
    return domains


def update_hosts(new_domains: set[str]) -> int:
    """Append new domains to HOSTS.txt. Returns count added."""
    path = Path(config.HOSTS_FILE)
    existing = load_existing_hosts_set()
    to_add = new_domains - existing
    if not to_add:
        return 0

    with path.open('a', encoding='utf-8') as f:
        f.write(f"\n# Auto-curated by ML pipeline on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n")
        for d in sorted(to_add):
            f.write(f"0.0.0.0 {d}\n")
    return len(to_add)


def regenerate_blocklist_json() -> int:
    """Regenerate blocklist.json (plain sorted domain array for extension)."""
    domains = sorted(load_existing_hosts_set())
    with open(config.BLOCKLIST_JSON, 'w', encoding='utf-8') as f:
        json.dump(domains, f, ensure_ascii=False, separators=(',', ':'))
    return len(domains)


def write_review_queue(review_items: list[tuple[str, float, str]]) -> None:
    """Write REVIEW_QUEUE.md with medium-confidence domains.

    Each item is (domain, score, source).
    """
    path = Path(config.REVIEW_QUEUE_FILE)
    with path.open('w', encoding='utf-8') as f:
        f.write("# Domain Review Queue\n\n")
        f.write(f"_Auto-generated by ML curation pipeline on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_\n\n")
        if not review_items:
            f.write("_No domains currently pending review._\n")
            return
        f.write("These domains scored between the review threshold and the auto-merge threshold.\n")
        f.write("A human maintainer should review and either add to `data/HOSTS.txt` or reject.\n\n")
        f.write("| Domain | Score | Source |\n")
        f.write("|--------|------:|--------|\n")
        for domain, score, source in sorted(review_items, key=lambda x: (-x[1], x[0])):
            short_source = source if len(source) < 60 else source[:57] + "..."
            f.write(f"| `{domain}` | {score:.2f} | {short_source} |\n")
